export const resources = [
  {
    id: 1,
    title: "JavaScript Fundamentals Guide",
    type: "pdf",
    category: "Programming",
    size: 2.1,
    tags: ["js", "beginner"],
    date: "2026-04-01",
  },
  {
    id: 2,
    title: "Modern UI Design Principles",
    type: "image",
    category: "Design",
    size: 1.8,
    tags: ["ui", "figma"],
    date: "2026-04-02",
  },
  {
    id: 3,
    title: "CSS Grid & Flexbox Mastery",
    type: "pdf",
    category: "Programming",
    size: 3.5,
    tags: ["css", "layout"],
    date: "2026-04-03",
  },
  {
    id: 4,
    title: "UX Research Case Study Collection",
    type: "image",
    category: "Design",
    size: 2.0,
    tags: ["ux", "research"],
    date: "2026-04-04",
  },
  {
    id: 5,
    title: "React Component Architecture Patterns",
    type: "pdf",
    category: "Programming",
    size: 4.2,
    tags: ["react", "components"],
    date: "2026-04-05",
  },
  {
    id: 6,
    title: "Logo Design Inspiration Pack",
    type: "image",
    category: "Design",
    size: 1.5,
    tags: ["logo", "branding"],
    date: "2026-04-06",
  },
  {
    id: 7,
    title: "Node.js Backend Development Basics",
    type: "pdf",
    category: "Programming",
    size: 3.1,
    tags: ["node", "backend"],
    date: "2026-04-07",
  },
  {
    id: 8,
    title: "Typography & Font Pairing Guide",
    type: "image",
    category: "Design",
    size: 2.3,
    tags: ["typography", "fonts"],
    date: "2026-04-08",
  },
  {
    id: 9,
    title: "Git Version Control Essentials",
    type: "pdf",
    category: "Programming",
    size: 2.7,
    tags: ["git", "version"],
    date: "2026-04-09",
  },
  {
    id: 10,
    title: "Color Theory for UI Designers",
    type: "image",
    category: "Design",
    size: 1.9,
    tags: ["color", "design"],
    date: "2026-04-10",
  },

  {
    id: 11,
    title: "REST API Integration Guide",
    type: "pdf",
    category: "Programming",
    size: 3.4,
    tags: ["api", "fetch"],
    date: "2026-04-11",
  },
  {
    id: 12,
    title: "Mobile App UI Inspiration Kit",
    type: "image",
    category: "Design",
    size: 2.1,
    tags: ["mobile", "ui"],
    date: "2026-04-12",
  },
  {
    id: 13,
    title: "JavaScript Array Methods Explained",
    type: "pdf",
    category: "Programming",
    size: 4.0,
    tags: ["array", "js"],
    date: "2026-04-13",
  },
  {
    id: 14,
    title: "Wireframing Techniques for UX",
    type: "image",
    category: "Design",
    size: 1.6,
    tags: ["wireframe", "ux"],
    date: "2026-04-14",
  },
  {
    id: 15,
    title: "Python Programming for Beginners",
    type: "pdf",
    category: "Programming",
    size: 2.9,
    tags: ["python", "beginner"],
    date: "2026-04-15",
  },
  {
    id: 16,
    title: "Creative Branding Strategy Guide",
    type: "image",
    category: "Design",
    size: 2.4,
    tags: ["branding", "ideas"],
    date: "2026-04-16",
  },
  {
    id: 17,
    title: "Database Design Fundamentals",
    type: "pdf",
    category: "Programming",
    size: 3.8,
    tags: ["db", "sql"],
    date: "2026-04-17",
  },
  {
    id: 18,
    title: "Digital Illustration Techniques",
    type: "image",
    category: "Design",
    size: 2.2,
    tags: ["illustration", "art"],
    date: "2026-04-18",
  },
  {
    id: 19,
    title: "Asynchronous JavaScript Deep Dive",
    type: "pdf",
    category: "Programming",
    size: 4.3,
    tags: ["async", "promises"],
    date: "2026-04-19",
  },
  {
    id: 20,
    title: "Figma Component System Guide",
    type: "image",
    category: "Design",
    size: 1.7,
    tags: ["figma", "components"],
    date: "2026-04-20",
  },

  {
    id: 21,
    title: "Object-Oriented Programming in JS",
    type: "pdf",
    category: "Programming",
    size: 3.2,
    tags: ["oop", "js"],
    date: "2026-04-21",
  },
  {
    id: 22,
    title: "Design System Building Blocks",
    type: "image",
    category: "Design",
    size: 2.6,
    tags: ["design", "system"],
    date: "2026-04-22",
  },
  {
    id: 23,
    title: "Frontend Performance Optimization Tips",
    type: "pdf",
    category: "Programming",
    size: 3.6,
    tags: ["performance", "web"],
    date: "2026-04-23",
  },
  {
    id: 24,
    title: "Sketching UI Ideas Workbook",
    type: "image",
    category: "Design",
    size: 1.4,
    tags: ["sketch", "ui"],
    date: "2026-04-24",
  },
  {
    id: 25,
    title: "RESTful API Design Principles",
    type: "pdf",
    category: "Programming",
    size: 2.8,
    tags: ["api", "rest"],
    date: "2026-04-25",
  },
  {
    id: 26,
    title: "Icon Design Essentials Pack",
    type: "image",
    category: "Design",
    size: 2.0,
    tags: ["icons", "design"],
    date: "2026-04-26",
  },
  {
    id: 27,
    title: "TypeScript Beginner to Advanced",
    type: "pdf",
    category: "Programming",
    size: 3.7,
    tags: ["ts", "js"],
    date: "2026-04-27",
  },
  {
    id: 28,
    title: "Landing Page UI Inspiration Set",
    type: "image",
    category: "Design",
    size: 2.5,
    tags: ["landing", "ui"],
    date: "2026-04-28",
  },
  {
    id: 29,
    title: "Web Security Best Practices",
    type: "pdf",
    category: "Programming",
    size: 4.1,
    tags: ["security", "web"],
    date: "2026-04-29",
  },
  {
    id: 30,
    title: "Poster Design Creative Collection",
    type: "image",
    category: "Design",
    size: 1.8,
    tags: ["poster", "design"],
    date: "2026-04-30",
  },

  {
    id: 31,
    title: "Graph Algorithms Explained Clearly",
    type: "pdf",
    category: "Programming",
    size: 3.9,
    tags: ["graphs", "algo"],
    date: "2026-03-01",
  },
  {
    id: 32,
    title: "Color Palette Inspiration Board",
    type: "image",
    category: "Design",
    size: 2.1,
    tags: ["palette", "color"],
    date: "2026-03-02",
  },
  {
    id: 33,
    title: "JavaScript Testing with Jest Guide",
    type: "pdf",
    category: "Programming",
    size: 3.3,
    tags: ["testing", "js"],
    date: "2026-03-03",
  },
  {
    id: 34,
    title: "UX Case Study Analysis Pack",
    type: "image",
    category: "Design",
    size: 2.4,
    tags: ["ux", "case"],
    date: "2026-03-04",
  },
  {
    id: 35,
    title: "Webpack Module Bundling Basics",
    type: "pdf",
    category: "Programming",
    size: 2.7,
    tags: ["webpack", "build"],
    date: "2026-03-05",
  },
  {
    id: 36,
    title: "Modern Layout Design Examples",
    type: "image",
    category: "Design",
    size: 2.3,
    tags: ["layout", "design"],
    date: "2026-03-06",
  },
  {
    id: 37,
    title: "Functional Programming Concepts JS",
    type: "pdf",
    category: "Programming",
    size: 4.4,
    tags: ["fp", "js"],
    date: "2026-03-07",
  },
  {
    id: 38,
    title: "Minimal UI Kit Collection",
    type: "image",
    category: "Design",
    size: 1.6,
    tags: ["ui", "kit"],
    date: "2026-03-08",
  },
  {
    id: 39,
    title: "Browser APIs Deep Guide",
    type: "pdf",
    category: "Programming",
    size: 3.5,
    tags: ["browser", "api"],
    date: "2026-03-09",
  },
  {
    id: 40,
    title: "Dashboard UI Design System",
    type: "image",
    category: "Design",
    size: 2.8,
    tags: ["dashboard", "ui"],
    date: "2026-03-10",
  },

  {
    id: 41,
    title: "JavaScript Event Loop Explained",
    type: "pdf",
    category: "Programming",
    size: 3.1,
    tags: ["eventloop", "js"],
    date: "2026-03-11",
  },
  {
    id: 42,
    title: "Advanced Illustration Techniques Pack",
    type: "image",
    category: "Design",
    size: 2.2,
    tags: ["illustration", "pack"],
    date: "2026-03-12",
  },
  {
    id: 43,
    title: "DOM Manipulation Masterclass",
    type: "pdf",
    category: "Programming",
    size: 4.2,
    tags: ["dom", "js"],
    date: "2026-03-13",
  },
  {
    id: 44,
    title: "Typography Pairing Systems Guide",
    type: "image",
    category: "Design",
    size: 1.9,
    tags: ["fonts", "pairing"],
    date: "2026-03-14",
  },
  {
    id: 45,
    title: "Clean Code Writing Principles",
    type: "pdf",
    category: "Programming",
    size: 3.6,
    tags: ["clean", "code"],
    date: "2026-03-15",
  },
  {
    id: 46,
    title: "UI Animation Design Basics",
    type: "image",
    category: "Design",
    size: 2.0,
    tags: ["animation", "ui"],
    date: "2026-03-16",
  },
  {
    id: 47,
    title: "State Management in JavaScript",
    type: "pdf",
    category: "Programming",
    size: 3.7,
    tags: ["state", "js"],
    date: "2026-03-17",
  },
  {
    id: 48,
    title: "Color System Design Guide",
    type: "image",
    category: "Design",
    size: 1.9,
    tags: ["color", "system"],
    date: "2026-03-18",
  },
  {
    id: 49,
    title: "Fullstack Developer Roadmap 2026",
    type: "pdf",
    category: "Programming",
    size: 5.2,
    tags: ["roadmap", "career"],
    date: "2026-03-19",
  },
  {
    id: 50,
    title: "Creative Design Thinking Workbook",
    type: "image",
    category: "Design",
    size: 2.6,
    tags: ["creative", "design"],
    date: "2026-03-20",
  },
];

export function saveUsers(userData) {
  users.push(userData);
  localStorage.setItem("users", JSON.stringify(users));
}
export function currentUser(userData) {
  localStorage.setItem("currentUser", JSON.stringify(userData));
}
